// DIGIT_0
//  SEG A:  D1  TONE MANUAL
//  SEG B:  D2  LFO-1 WAVEFORM: TRIANGLE
//  SEG C:  D3  LFO-1 WAVEFORM: SAW
//  SEG D:  D4  LFO-1 WAVEFORM: SQUARE
//  SEG E:  D5  LFO-1 WAVEFORM: RANDOM
//  SEG F:  D6  PWM SOURCE: ENV-1
//  SEG G:  D7  PWM SOURCE: LFO-1
//  SEG DP: D8  PWM SOURCE: KYBD
// DIGIT_1
//  SEG A:  D9  VCO-1 WAVEFORM: PWM
//  SEG B:  D10 VCO-1 WAVEFORM: SQUARE
//  SEG C:  D11 SYNC VCO-1 -> VCO-2
//  SEG D:  D12 SYNC VCO-1 <- VCO-2
//  SEG E:  D13 VCO-2 MOD: NORM
//  SEG F:  D14 VCO-2 MOD: INV
//  SEG G:  D15 VCO-2 WAVEFORM: TRIANGLE
//  SEG DP: D16 VCO-2 WAVEFORM: SAW
// DIGIT_2
//  SEG A:  D17 PWM POL INV
//  SEG B:  D18 KEY FOLLOW: VCO-1
//  SEG C:  D19 KEY FOLLOW: VCO-2
//  SEG D:  D20 VCO-1 MOD: ENV-1 POL INV
//  SEG E:  D21 VCO-1 MOD: NORM
//  SEG F:  D22 VCO-1 MOD: INV
//  SEG G:  D23 VCO-1 WAVEFORM: TRIANGLE
//  SEG DP: D24 VCO-1 WAVEFORM: SAW
// DIGIT_3
//  SEG A:  D25 VCO-2 WAVEFORM: PWM
//  SEG B:  D26 VCO-2 WAVEFORM: NOISE
//  SEG C:  D27 VCF ENV: ENV-1
//  SEG D:  D28 VCF ENV: ENV-2
//  SEG E:  D29 VCF ENV: POL INV
//  SEG F:  D30 ENV RESET
//  SEG G:  D31 ENV-1: DYNAMICS
//  SEG DP: D32 ENV-2: DYNAMICS
// DIGIT_4
//  SEG A:  D33 PATCH MANUAL
//  SEG B:  D34 KEY MODE: WHOLE
//  SEG C:  D35 KEY MODE: SPLIT-2
//  SEG D:  D36 KEY MODE: SPLIT-1
//  SEG E:  D37 KEY MODE: DUAL
//  SEG F:  D38 OCT SHIFT: -2
//  SEG G:  D39 OCT SHIFT: -1
//  SEG DP: D40 OCT SHIFT: 0
// DIGIT_5
//  SEG A:  D41 OCT SHIFT: +1
//  SEG B:  D42 OCT SHIFT: +2
//  SEG C:  D43 ASSIGN MODE: SOLO
//  SEG D:  D44 ASSIGN MODE: UNISSON-1
//  SEG E:  D45 ASSIGN MODE: UNISSON-2
//  SEG F:  D46 ASSIGN MODE: POLY-1
//  SEG G:  D47 ASSIGN MODE: POLY-2
//  SEG DP: D48 ASSIGN MODE: HOLD ON
// DIGIT_6
//  SEG A:  D49 ASSIGN MODE: HOLD MIDI
//  SEG B:  D50 BENDER: VCO-1 WIDE
//  SEG C:  D51 BENDER: VCO-1 NORM
//  SEG D:  D52 BENDER: VCO-2 WIDE
//  SEG E:  D53 BENDER: VCO-2 NORM
//  SEG F:  D54 AFTER-TOUCH: VCO-MOD
//  SEG G:  D55 AFTER-TOUCH: VCF-FREQ
//  SEG DP: D56 ARPEGGIO: MODE ON
// DIGIT_7
//  SEG A:  D57 ARPEGGIO: SYNC EXT
//  SEG B:  D58 ARPEGGIO: SYNC MIDI
//  SEG C:  D59 TONE SELECT: LOWER
//  SEG D:  D60 TONE SELECT: UPPER
//  SEG E:  (not used)
//  SEG F:  (not used)
//  SEG G:  (not used)
//  SEG DP: (not used)

